language: node_js
node_js:
  - "node"
  - "6"
script: npm run lint
deploy:
  provider: npm
  email: trevordmiller@icloud.com
  api_key:
    secure: mEAVDslZxgz3ojUMSkZeDe9lNovLR5qssND+VzbpHcatVD0zwh2BX3qo1q23lVHzV54qNeWwTL1x0/wWtGp2g+YWhyBgDrqQEnY3+i/+XNc2+Slo8uIbuCzqiKLgH6N4AR3/TqVIsLwWzEqmOo4CP+5ywYP/5maKiUMiDK0UriKRDPN8Ts3VIYSDrLx7210EfpUD8YGbX6ccQ+tl1fB1jE/DIxPlNLL37nicgZLKb4igWmN2ZAv7XThuNCTN2vzAhEi92oenESzXg75v3PpYfqucTQQ2frnk9DhSGcfdYz3iYTdiwq+/4Gw6TkEa+1Ottk/UkHlp078ibu1SiPmIMnMvwtrpYZnviGuG0tGQ4JChjNoqIZpqjOoaCH661IKtnjUdEzTmQu/+y+h9bw9l6dR0+GD2ejiTsehj2/2wIrnAz9NjCxW2yDKUk7W6le2NhDvzrw+ZRrRB7L8+dgUSTbxw0e7xICLkYVWvHdqHEs21uHrmMOXyC4g8pn+ulCloQxWZxiV52w7GDDr2oUNzEpTbIKHaQk5CjOCzu2hCRZdCP+NOO+whk1WrT9pm8YqrCJk4fh82t5oSLvrhwoJrKoy9tLDvKw0qKgvOuGa6QKxryPebTv1bVWnckYb1RGYRpP8yEVrvoHy8NtsP2DpEPemr8ymq9XuTYsTpcYWuoRs=
  on:
    repo: trevordmiller/nova-hyperterm
    branch: master
