language: node_js
node_js:
- node
- '6'
script: npm run build
deploy:
  provider: npm
  email: trevordmiller@icloud.com
  api_key:
    secure: dgNdq5lkjimtsAsxl4SCscZQRC4RyUYcosiGJPrLGvikzbPpaJ/rvMI26nrkr7EgCR+MdRRBYvIS7SVi+/uyOmM+FaRnxbLufhziJ7rdUKEZh7eezt7O/52Z255Loj18H5hgcz9Qgvs+pqIC0ZeqjzWZgZwGqAP7r97Nlipr6sKz45bBHqJwaxjIC+YKRDuWWwFuc5oBDb+cmf323lzz/qYb1NXFDNGC8jRwCc6GY158hfD4c5FNHwNANE3F6MWACVDO7RC/tarsVcRMKNpF40xTQF+0NnDRiVNPA0N8a2m+Bq8L3n1P+S/9TJwmkDmKGurIA6nzA8clNwu1u37IylO4C1NkDdWXCdoL3Nr7HQ6R0gkxVoSdoukuYO2LT75ppw4KMnDcTKZlCDgvPadOHWe/yWodzDcAmNGr9bUV1nz0ejCjlQ3O1qbz653GCmZo7DyxvQIrOsDgukDgj6j6C7SiCY4CjvaIFXFX4vn6i8aRuZtFMHN9AztwgL5sW20VKAM98jO6eN73s9POasbMbqfuL5BkSkSVELJiuZGD7pd4hLof/brgw04d8UYrVvrRLKX7nUoa/Y0wd4j+J6WNKTqohJPCDuhDK+aRFGm+EeKTGp15M6I+Sck9vS5pQnVhu/y12Uyfuv+FcrCX23tSFlXK+QMz9ZZ7xmqQwil4snw=
  on:
    repo: trevordmiller/nova-hyperterm
    tags: true
